version: '3'
services:
  app:
    image: nederbg/kaddem:1.0
    restart: unless-stopped
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    volumes:
      - app_data:/var/lib/mysql  -

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  app_data:
  mysql_data: