version: '3'
services:
  app:
    image: nederbg/kaddem:1.0
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - mysql
    volumes:
      - app_data:/var/lib/app  -

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  app_data:
  mysql_data: