version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"

  app:
    image: nederbg/kaddem:1.0
    ports:
      - "8083:8083"
    depends_on:
      - mysql