version: "3.9"
services:

  kaddem:
    container_name: kaddem
    image: "kaddem"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/kaddem?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      - mysql-container
    volumes:
      - kaddem-data:/kaddem-data
    networks:
      - spring-network



  mysql-container:
    image: "mysql:5.6"
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: kaddem
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - mysql_data:/opt/mysql/data
    networks:
      - spring-network

networks:
  spring-network:
volumes:
  kaddem-data:
  mysql_data:


